logging:
  level:
    org:
      hibernate:
        # 把SpringBoot的Hibernate的debug信息打开
        SQL: debug

spring:
  datasource:
    driverClassName: org.h2.Driver
    # 数据库的名称 当使用embedded database的时候默认testdb
    name: testdb
    # 配置连接数据库的密码 h2数据库默认没有密码
    password: ''
    # 数据初始化的功能
    url: jdbc:h2:tcp://localhost:9092/mem:testdb
    # 配置连接数据库的用户名 h2数据库 默认 sa
    username: sa
    initializationMode: never

  flyway:
    baseline-on-migrate: true
  h2:
    console:
      #配置项目启动 h2就启动
      enabled: true
      #配置访问地址 默认就是 /h2-console
      path: /h2-console
      settings:
        trace: true
        #配置能远程访问
        web-allow-others: true
  jpa:
    # 数据库类型声明
    database: h2
    hibernate:
      # ddl-auto:create----每次运行该程序，没有表格会新建表格，表内有数据会清空
      # ddl-auto:create-drop----每次程序结束的时候会清空表
      # ddl-auto:update----每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
      # ddl-auto:validate----运行程序会校验数据与数据库的字段类型是否相同，不同会报错
      ddl-auto: validate
    open-in-view: true
    # 是否开启查询语句在控制台打印
    show-sql: true

  # QuartzAutoConfiguration
  quartz:
    # 持久化到数据库方式
    job-store-type: jdbc
    # 初始化表结构
    jdbc:
      initialize-schema: never
    # 相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true